// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahzhkzqsaxvzixiivupb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoemhrenFzYXh2eml4aWl2dXBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTc1ODMsImV4cCI6MjA3Mzc5MzU4M30.wu_lKG279SSMKdggRoCkIxiGIuFrmINI5OOUpBsST5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});